### ISSUE TITLE
Hey how did you manage NPSSO-TOKEN everytime . Can you please tell me after login and logout my npsso token changed for that account. How we can manage that

### ISSUE THREAD

**Issue by jsnic-github** [evanshortiss/evanshortiss#1]

**Comment by evanshortiss** [comment]
@jsnic-github can you use the description area for the issue to explain what your issue is step-by-step? Thanks.

**Comment by evanshortiss** [comment]
Closing this issue. Feel free to reopen if you need to, and can provide a better description.
